### PR TITLE
Add oauth jwt token facade

### PR DESCRIPTION
**Pull request by tobiastrinks**
# What?

Add JWT token validation and authority handling.

# Why?

To deny access to anybody without a valid access-token.

# How?

We can merge this as soon as the access-points implemented authentication.

### CODE REVIEW

**Review by 8BitJonny — APPROVED** [review]
👍

**Comment by tobiastrinks** [comment]
outdated

**Comment by lukas-vollmer** [comment]
its never to late

**Comment by lukas-vollmer** [comment]
@tobiastrinks looks like a job made for you

**Comment by tobiastrinks** [comment]
I really enjoy the strong community behind this open source project. Thanks for reopening @lukas-vollmer @ConstantinSchreiber, I hope this fixes the "bug".

**Comment by lukas-vollmer** [comment]
thanks, good job

**Comment by 8BitJonny** [comment]
👍

**Pull request merged**
